/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imnsu.publico;

import Dao.personaDao;
import Dao.tipoEstudioDao;
import Vo.PersonaVo;
import Vo.tipoEstadoVo;
import Vo.tipoEstudioVo;
import java.awt.Component;
import java.sql.Timestamp;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.text.NumberFormatter;
import resources.img.ArrayListComboBoxModel;
import resources.img.formato;
import resources.img.ingreso;

public class jdPersona extends javax.swing.JDialog {

    private final formato ff = new formato();
    private final boolean editar;
    private final ingreso in;

    /**
     * Creates new form jdPersona
     *
     * @param parent
     * @param modal
     * @param in
     * @param editar
     */
    public jdPersona(java.awt.Frame parent, boolean modal, ingreso in, boolean editar) {
        super(parent, modal);
        initComponents();
        this.in=in;
        setCbTipoEstudio();
        this.editar = editar;
        this.setSize(550, 380);
        this.setLocationRelativeTo(parent);
        setCbTipoEstado();
        if (this.editar) {
            jtfNombre.setText(in.persona.getNombre());
            jtfPaterno.setText(in.persona.getPaterno());
            jtfMaterno.setText(in.persona.getMaterno());
            jftfEdad.setText(String.valueOf(in.persona.getEdad()));
            jcbTipoEstado.setSelectedItem(in.persona.getTipoestado());
            jcbSexo.setSelectedItem(in.persona.getSex());
            tipoEstadoVo tipoestado = tipoEstadoDao1.getTipoEstado(in.persona.getIdtipoestado());
            //jcbTipoEstado.setSelectedIndex(0);
            jcbTipoEstado.getModel().setSelectedItem(tipoestado);
            jchOrigen.setSelected(in.persona.isInterior());
            jtfOrigen.setEnabled(in.persona.isInterior());
            jtfOrigen.setText(in.persona.getProcedencia());
            jtfTelefono.setText(in.persona.getTelefono());
            jtffonoreponsalble.setText(in.persona.getTelefonoresponsable());
            jtfMedico.setText(in.persona.getMedicoremitente());
            jtfInstitucion.setText(in.persona.getInstituicionprocedente());
            jchEnespera.setSelected(in.persona.isEnespera());
            jxdpFechaEspera.setDate(in.persona.getFechainicioespera());
            jxdpFechaTentativa.setDate(in.persona.getFechatentativa());
            tipoEstudioVo tipoestudio = new tipoEstudioDao().getTipoEstudio(in.persona.getIdtipoestudiosolicitado());
            jcbTipoEstudio.getModel().setSelectedItem(tipoestudio);
        }
    }

    private void setCbTipoEstado() {
        jcbTipoEstado.removeAll();
        ArrayListComboBoxModel model = new ArrayListComboBoxModel(tipoEstadoDao1.comboTipoEstado());
        jcbTipoEstado.setModel(model);
        DefaultListCellRenderer renderer = new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof tipoEstadoVo) {
                    tipoEstadoVo tipoestadoVo = (tipoEstadoVo) value;
                    setText(tipoestadoVo.getDescripcion());
                }
                return this;
            }
        };
        jcbTipoEstado.setRenderer(renderer);
        jcbTipoEstado.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoEstadoDao1 = new Dao.tipoEstadoDao();
        personaDao1 = new Dao.personaDao();
        tipoEstudioDao1 = new Dao.tipoEstudioDao();
        jXHeader1 = new org.jdesktop.swingx.JXHeader();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfPaterno = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfMaterno = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jftfEdad = new JFormattedTextField(ff.getFormatoEntero());
        NumberFormatter nf1 = (NumberFormatter)jftfEdad.getFormatter();
        nf1.setOverwriteMode(false);
        nf1.setAllowsInvalid(false);
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jcbSexo = new javax.swing.JComboBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jcbTipoEstado = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jchOrigen = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        jtfOrigen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtfTelefono = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jtffonoreponsalble = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtfMedico = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtfInstitucion = new javax.swing.JTextField();
        jchEnespera = new javax.swing.JCheckBox();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jxdpFechaEspera = new org.jdesktop.swingx.JXDatePicker();
        jPanel22 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jxdpFechaTentativa = new org.jdesktop.swingx.JXDatePicker();
        jPanel23 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jcbTipoEstudio = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jXHeader1.setTitle("Persona");
        getContentPane().add(jXHeader1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(new java.awt.GridLayout(3, 1));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setText(" Nombre: ");
        jLabel1.setPreferredSize(new java.awt.Dimension(70, 0));
        jPanel4.add(jLabel1, java.awt.BorderLayout.WEST);
        jPanel4.add(jtfNombre, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setText(" Paterno: ");
        jLabel2.setPreferredSize(new java.awt.Dimension(70, 0));
        jPanel5.add(jLabel2, java.awt.BorderLayout.WEST);
        jPanel5.add(jtfPaterno, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setText(" Materno: ");
        jLabel3.setPreferredSize(new java.awt.Dimension(70, 0));
        jPanel6.add(jLabel3, java.awt.BorderLayout.WEST);
        jPanel6.add(jtfMaterno, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel6);

        jPanel1.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setPreferredSize(new java.awt.Dimension(200, 0));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("   Edad: ");
        jLabel4.setPreferredSize(new java.awt.Dimension(60, 0));
        jPanel7.add(jLabel4, java.awt.BorderLayout.WEST);

        jftfEdad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftfEdad.setText("1");
        jftfEdad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfEdadFocusGained(evt);
            }
        });
        jPanel7.add(jftfEdad, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("   Sexo: ");
        jLabel5.setPreferredSize(new java.awt.Dimension(60, 0));
        jPanel8.add(jLabel5, java.awt.BorderLayout.WEST);

        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        jPanel8.add(jcbSexo, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel6.setText(" Condición");
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 0));
        jPanel9.add(jLabel6, java.awt.BorderLayout.WEST);

        jPanel9.add(jcbTipoEstado, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel11, java.awt.BorderLayout.EAST);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Adicionales"));
        jPanel3.setLayout(new java.awt.GridLayout(5, 1));

        jPanel12.setLayout(new java.awt.BorderLayout());

        jchOrigen.setText("Interior");
        jchOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchOrigenActionPerformed(evt);
            }
        });
        jPanel12.add(jchOrigen, java.awt.BorderLayout.WEST);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jtfOrigen.setText("Sucre");
        jtfOrigen.setEnabled(false);
        jPanel13.add(jtfOrigen, java.awt.BorderLayout.CENTER);

        jLabel7.setText("       Origen: ");
        jPanel13.add(jLabel7, java.awt.BorderLayout.WEST);

        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel8.setText("  Telefono: ");
        jPanel14.add(jLabel8, java.awt.BorderLayout.WEST);

        jtfTelefono.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfTelefono.setPreferredSize(new java.awt.Dimension(90, 0));
        jPanel14.add(jtfTelefono, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel14, java.awt.BorderLayout.EAST);

        jPanel12.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel12);

        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel9.setText("Responsable: ");
        jPanel16.add(jLabel9, java.awt.BorderLayout.WEST);

        jtffonoreponsalble.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtffonoreponsalble.setPreferredSize(new java.awt.Dimension(90, 0));
        jPanel16.add(jtffonoreponsalble, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel16, java.awt.BorderLayout.WEST);

        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel10.setText("  Médico: ");
        jLabel10.setPreferredSize(new java.awt.Dimension(70, 0));
        jPanel17.add(jLabel10, java.awt.BorderLayout.WEST);
        jPanel17.add(jtfMedico, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel15);

        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel11.setText("Institución: ");
        jLabel11.setPreferredSize(new java.awt.Dimension(70, 0));
        jPanel19.add(jLabel11, java.awt.BorderLayout.WEST);
        jPanel19.add(jtfInstitucion, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel19, java.awt.BorderLayout.CENTER);

        jchEnespera.setSelected(true);
        jchEnespera.setText("En espera");
        jchEnespera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchEnesperaActionPerformed(evt);
            }
        });
        jPanel18.add(jchEnespera, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel18);

        jPanel20.setLayout(new java.awt.GridLayout(1, 0));

        jPanel21.setLayout(new java.awt.BorderLayout());

        jLabel12.setText("Fecha Inicio Espera: ");
        jPanel21.add(jLabel12, java.awt.BorderLayout.WEST);
        jPanel21.add(jxdpFechaEspera, java.awt.BorderLayout.CENTER);

        jPanel20.add(jPanel21);

        jPanel22.setLayout(new java.awt.BorderLayout());

        jLabel13.setText("Fecha Tentativa: ");
        jPanel22.add(jLabel13, java.awt.BorderLayout.WEST);
        jPanel22.add(jxdpFechaTentativa, java.awt.BorderLayout.CENTER);

        jPanel20.add(jPanel22);

        jPanel3.add(jPanel20);

        jPanel23.setLayout(new java.awt.BorderLayout());

        jLabel14.setText("Estudio Solicitado: ");
        jPanel23.add(jLabel14, java.awt.BorderLayout.WEST);

        jcbTipoEstudio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbTipoEstudio.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcbTipoEstudioPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jcbTipoEstudio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcbTipoEstudioKeyReleased(evt);
            }
        });
        jPanel23.add(jcbTipoEstudio, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel23);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        if (!this.editar) {
            this.in.persona = new PersonaVo();
        }
        this.in.persona.setNombre(jtfNombre.getText());
        this.in.persona.setPaterno(jtfPaterno.getText());
        this.in.persona.setMaterno(jtfMaterno.getText());
        this.in.persona.setIdtipoestado(((tipoEstadoVo) jcbTipoEstado.getSelectedItem()).getId());
        
        this.in.persona.setSexo((jcbSexo.getSelectedItem().toString().compareTo("Masculino") == 0) ? "M" : "F");
        this.in.persona.setEdad(Integer.parseInt(jftfEdad.getText()));

        this.in.persona.setInterior(jchOrigen.isSelected());
        this.in.persona.setProcedencia(jtfOrigen.getText());
        this.in.persona.setTelefono(jtfTelefono.getText());
        this.in.persona.setTelefonoresponsable(jtffonoreponsalble.getText());
        this.in.persona.setMedicoremitente(jtfMedico.getText());
        this.in.persona.setInstituicionprocedente(jtfInstitucion.getText());
        this.in.persona.setEnespera(jchEnespera.isSelected());
        this.in.persona.setFechainicioespera(new Timestamp(jxdpFechaEspera.getDate().getTime()));
        this.in.persona.setFechatentativa(new Timestamp(jxdpFechaTentativa.getDate().getTime()));
        this.in.persona.setIdtipoestudiosolicitado(((tipoEstudioVo)jcbTipoEstudio.getSelectedItem()).getId());
        if (this.editar) {
            personaDao.updatePersona(in.persona);
        } else {
            personaDao.insertPersona(in.persona);
        }
        JOptionPane.showMessageDialog(new JFrame(), "Registro Exitoso!!!");
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jftfEdadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfEdadFocusGained
        // TODO add your handling code here:
        jftfEdad.selectAll();
    }//GEN-LAST:event_jftfEdadFocusGained

    private void jchOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchOrigenActionPerformed
        // TODO add your handling code here:
        jtfOrigen.setEnabled(jchOrigen.isSelected());
    }//GEN-LAST:event_jchOrigenActionPerformed

    private void jchEnesperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchEnesperaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchEnesperaActionPerformed

    private void jcbTipoEstudioPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbTipoEstudioPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
//        tipoEstudioVo tipoestudio = (tipoEstudioVo) jcbTipoEstudio.getSelectedItem();
//        jlRadio.setText(" ***Radio Farmaco: " + tipoestudio.getRadiofarmaco());
//        jlDosis.setText("Dosis: " + tipoestudio.getDosis());
    }//GEN-LAST:event_jcbTipoEstudioPopupMenuWillBecomeInvisible

    private void jcbTipoEstudioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbTipoEstudioKeyReleased
        // TODO add your handling code here:
//        tipoEstudioVo tipoestudio = (tipoEstudioVo) jcbTipoEstudio.getSelectedItem();
//        jlRadio.setText(" ***Radio Farmaco: " + tipoestudio.getRadiofarmaco());
//        jlDosis.setText("Dosis: " + tipoestudio.getDosis());
    }//GEN-LAST:event_jcbTipoEstudioKeyReleased
    private void setCbTipoEstudio() {
        jcbTipoEstudio.removeAll();
        ArrayListComboBoxModel model = new ArrayListComboBoxModel(tipoEstudioDao1.comboTipoEstudio());
        jcbTipoEstudio.setModel(model);
        DefaultListCellRenderer renderer = new DefaultListCellRenderer() {
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof tipoEstudioVo) {
                    tipoEstudioVo tipoestadoVo = (tipoEstudioVo) value;
                    setText(tipoestadoVo.getDescripcion());
                }
                return this;
            }
        };
        jcbTipoEstudio.setRenderer(renderer);
        jcbTipoEstudio.updateUI();
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    private javax.swing.JComboBox jcbSexo;
    private javax.swing.JComboBox jcbTipoEstado;
    private javax.swing.JComboBox jcbTipoEstudio;
    private javax.swing.JCheckBox jchEnespera;
    private javax.swing.JCheckBox jchOrigen;
    private javax.swing.JFormattedTextField jftfEdad;
    private javax.swing.JTextField jtfInstitucion;
    private javax.swing.JTextField jtfMaterno;
    private javax.swing.JTextField jtfMedico;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfOrigen;
    private javax.swing.JTextField jtfPaterno;
    private javax.swing.JTextField jtfTelefono;
    private javax.swing.JTextField jtffonoreponsalble;
    private org.jdesktop.swingx.JXDatePicker jxdpFechaEspera;
    private org.jdesktop.swingx.JXDatePicker jxdpFechaTentativa;
    private Dao.personaDao personaDao1;
    private Dao.tipoEstadoDao tipoEstadoDao1;
    private Dao.tipoEstudioDao tipoEstudioDao1;
    // End of variables declaration//GEN-END:variables
}
