/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imnsu.publico;

import Dao.usuarioDao;
import Vo.usuarioVo;


public class jdUsuario extends javax.swing.JDialog {
private usuarioVo usuario;
private final boolean editar;
    /**
     * Creates new form jdUsuario
     * @param parent
     * @param modal
     * @param usuario
     * @param editar
     */
    public jdUsuario(java.awt.Frame parent, boolean modal, usuarioVo usuario, boolean editar) {
        super(parent, modal);
        initComponents();
        this.setSize(550, 470);
        this.setLocationRelativeTo(parent);        
        this.usuario=usuario;
        this.editar=editar;
        if(this.editar){
            jtfNombre.setText(this.usuario.getNombrecompleto());
            jtfUsuario.setText(this.usuario.getUsuario());
            jtfPass.setText(this.usuario.getPassword());
            jchPersona.setSelected(this.usuario.isOp1());
            jchListaPersonas.setSelected(this.usuario.isOp2());
            jchRecepcion.setSelected(this.usuario.isOp3());
            jchContra.setSelected(this.usuario.isOp4());
            jchAdmPermisos.setSelected(this.usuario.isOp5());
            jchAgenda.setSelected(this.usuario.isOp6());
            jchControl.setSelected(this.usuario.isOp7());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXHeader1 = new org.jdesktop.swingx.JXHeader();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfPass = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jchPersona = new javax.swing.JCheckBox();
        jchListaPersonas = new javax.swing.JCheckBox();
        jchRecepcion = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jchContra = new javax.swing.JCheckBox();
        jchAdmPermisos = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jchAgenda = new javax.swing.JCheckBox();
        jchControl = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jXHeader1.setTitle("Usuario");
        getContentPane().add(jXHeader1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setText(" Nombre Completo: ");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel3.add(jLabel1, java.awt.BorderLayout.WEST);
        jPanel3.add(jtfNombre, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Usuario: ");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel4.add(jLabel2, java.awt.BorderLayout.WEST);

        jtfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsuarioActionPerformed(evt);
            }
        });
        jPanel4.add(jtfUsuario, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Contraseña: ");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanel5.add(jLabel3, java.awt.BorderLayout.WEST);
        jPanel5.add(jtfPass, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Permisos"));
        jPanel7.setLayout(new java.awt.GridLayout(3, 1));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Archivo"));

        jchPersona.setText("Persona");
        jPanel8.add(jchPersona);

        jchListaPersonas.setText("Lista personas en Espera de estudio");
        jPanel8.add(jchListaPersonas);

        jchRecepcion.setText("Recepción de Material");
        jPanel8.add(jchRecepcion);

        jPanel7.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Mantenimiento"));

        jchContra.setText("Cambiar Contraseña");
        jPanel9.add(jchContra);

        jchAdmPermisos.setText("Administracion de Permisos");
        jPanel9.add(jchAdmPermisos);

        jPanel7.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Reportes"));

        jchAgenda.setText("Agenda de Programada");
        jPanel10.add(jchAgenda);

        jchControl.setText("Control de Material Radiactivo");
        jPanel10.add(jchControl);

        jPanel7.add(jPanel10);

        jPanel6.add(jPanel7, java.awt.BorderLayout.CENTER);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jPanel6.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel6, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.editar){
            this.usuario.setNombrecompleto(jtfNombre.getText());
            this.usuario.setUsuario(jtfUsuario.getText());
            this.usuario.setPassword(jtfPass.getText());
            this.usuario.setOp1(jchPersona.isSelected());
            this.usuario.setOp2(jchListaPersonas.isSelected());
            this.usuario.setOp3(jchRecepcion.isSelected());
            this.usuario.setOp4(jchContra.isSelected());
            this.usuario.setOp5(jchAdmPermisos.isSelected());
            this.usuario.setOp6(jchAgenda.isSelected());
            this.usuario.setOp7(jchControl.isSelected());
            this.usuario.setOp8(false);
            this.usuario.setOp9(false);
            this.usuario.setOp10(false);
            usuarioDao.updateusuario(usuario);
        }
        else{
            this.usuario=new usuarioVo(-999, jtfNombre.getText(),jtfUsuario.getText(), jtfPass.getText(), jchPersona.isSelected(), jchListaPersonas.isSelected(), jchRecepcion.isSelected(), jchContra.isSelected(),jchAdmPermisos.isSelected(), jchAgenda.isSelected(), jchControl.isSelected(), false, false, false);
            usuarioDao.insertUsuario(usuario);
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    private javax.swing.JCheckBox jchAdmPermisos;
    private javax.swing.JCheckBox jchAgenda;
    private javax.swing.JCheckBox jchContra;
    private javax.swing.JCheckBox jchControl;
    private javax.swing.JCheckBox jchListaPersonas;
    private javax.swing.JCheckBox jchPersona;
    private javax.swing.JCheckBox jchRecepcion;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JPasswordField jtfPass;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
